dist: xenial

language: python
cache: pip

notifications:
  email: false

matrix:
  include:
  - python: 2.7
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: 3.7

install: pip install -U pip tox-travis

script: tox
